Updated readme file for login
teachmind/Auth-service pull request #13
Opened 2021-07-17 14:46 UTC by rdhawladar

2021-07-18 08:40 UTC, shuza requested changes
use makefile to make steps simpler

2021-07-18 08:40 UTC, shuza commented on README.md
> +### Step-1
better to add single command like `make copy-config` using makefile

2021-07-18 08:40 UTC, shuza commented on README.md
> +### Step-2
better to add single command like `make migrate` using makefile

2021-07-18 08:40 UTC, shuza commented on README.md
> +### Step-3
better to add single command like `make server` using makefile

2021-07-19 05:13 UTC, zrshishir commented
It looks good to me

2021-07-19 05:14 UTC, zrshishir approved these changes
It looks good to me

2021-07-19 05:18 UTC, zrshishir reviewed
Project structure, Tools and Technology and Installation section should be added before the Feature Details section

2021-07-19 06:08 UTC, shuza approved these changes
lgtm. it will be better. if we can simplify commands using `Makefile` but we can do it in separate PR. I have create and issue for that https://github.com/teachmind/Auth-service/issues/14

2021-07-19 08:55 UTC, merged