Feature/ap 3
teachmind/Auth-service pull request #4
Opened 2021-06-26 16:00 UTC by zrshishir

Signup PR

2021-07-02 18:00 UTC, zrshishir commented on internal/pkg/postgres/db.go
> +	// println(conf.Url())
Removed

2021-07-10 16:34 UTC, shuza commented on internal/app/model/entities.go
> +	err := re.MatchString(user.PhoneNumber)
use correct name

2021-07-10 16:35 UTC, shuza requested changes
use proper variable name

2021-07-10 16:51 UTC, zrshishir commented on internal/app/model/entities.go
> +	err := re.MatchString(user.PhoneNumber)
changed

2021-07-10 18:41 UTC, rdhawladar requested changes
Please update the changes ASAP.

2021-07-10 18:41 UTC, rdhawladar commented on internal/app/model/entities.go
> +func (user *User) SignUpPhoneValidation() bool {
No need signupPhoneValidation, Should use the generic function PhoneValidation.

2021-07-10 18:41 UTC, rdhawladar commented on internal/app/user/service.go
> +	if user.PhoneNumber == "" || user.Password == "" {
all validation should be in a common function. You can rename and use ValidateLogin function in entity. But make sure that it doesn't break login validation.

2021-07-10 18:41 UTC, rdhawladar commented on internal/app/user/service.go
> +	if phoneNumber == "" || password == "" {
No need this validation. Handler.go is already validating by ValidateLogin() function.

2021-07-10 18:41 UTC, rdhawladar commented on internal/app/user/repository.go
> +	user.PhoneNumber = strings.ReplaceAll(user.PhoneNumber, "+88", "")
As you have changed the signup phoneNumber format, please update where this change has impact (like login validation and testcase input).

2021-07-10 18:41 UTC, rdhawladar commented on internal/app/user/repository.go
> +	user.PhoneNumber = strings.ReplaceAll(user.PhoneNumber, "+88", "")
if we are eliminating country code  why do we need this input from client? We can only check 01 and 11 digit. Shouldn't bother user for unnecessary input.

2021-07-11 13:46 UTC, zrshishir commented on go.mod
> +	github.com/go-playground/validator v9.31.0+incompatible // indirect
removed

2021-07-12 02:41 UTC, zrshishir commented on internal/app/model/entities.go
> +func (user *User) SignUpPhoneValidation() bool {
It is now generic validation for both signup and login

2021-07-12 02:41 UTC, zrshishir commented on internal/app/user/service.go
> +	if user.PhoneNumber == "" || user.Password == "" {
common validation function has been created

2021-07-12 02:42 UTC, zrshishir commented on internal/app/user/repository.go
> +	user.PhoneNumber = strings.ReplaceAll(user.PhoneNumber, "+88", "")
It is needed and i have added the removing country code and space with more sophisticated way. Please look over it.

2021-07-12 02:44 UTC, zrshishir commented on internal/app/user/repository.go
> +	user.PhoneNumber = strings.ReplaceAll(user.PhoneNumber, "+88", "")
As we discussed earlier we should allow country code and space because of different type of user input. Some people will input with space and country code and space. So, we keep it as validated.

2021-07-12 16:38 UTC, rdhawladar approved these changes
Looks good to me.

2021-07-12 17:08 UTC, zrshishir commented on internal/app/user/repository_test.go
> +		fmt.Println(err)
It has been remvoed.

2021-07-13 07:23 UTC, shuza requested changes
Remove IDE related files and address those comments

2021-07-13 07:23 UTC, shuza commented on internal/app/user/repository.go
> +	actualPhone := RMCodeAndSpace(phoneNumber)
where is the definition of this method?

2021-07-13 07:23 UTC, shuza commented on internal/app/server/halder_test.go
> +		expStatusCode int
also need to check response data

2021-07-13 13:43 UTC, zrshishir commented on internal/app/user/repository.go
> +	actualPhone := RMCodeAndSpace(phoneNumber)
below of the script at line 56

2021-07-13 13:45 UTC, zrshishir commented on internal/app/user/repository.go
> +	actualPhone := RMCodeAndSpace(phoneNumber)
IDE related file has been added on .gitignore file

2021-07-13 13:45 UTC, zrshishir commented on internal/app/server/halder_test.go
> +		expStatusCode int
response data added with test script

2021-07-13 16:44 UTC, rdhawladar approved these changes

2021-07-16 15:13 UTC, merged