Feature/ap 2
teachmind/Auth-service pull request #8
Opened 2021-07-02 14:52 UTC by Asad-noor

migration cascase issue fix.

2021-07-02 15:55 UTC, shuza commented on migrations/0001_add_tables.up.sql
> +          ON DELETE CASCADE
it is doing reverse deletion. if we delete any category from category table then it will delete users from user table which is not expected

2021-07-02 15:58 UTC, shuza requested changes
* category_id should not be delectable as long as it is used in user table
* Also fix the code catch by [codacy](https://app.codacy.com/gh/teachmind/Auth-service/pullRequest?prid=7698157)
<img width="621" alt="Screenshot 2021-07-02 at 9 57 29 PM" src="https://user-images.githubusercontent.com/10544274/124300537-8181db00-db80-11eb-9cc9-d5c4e59be5bb.png">

2021-07-02 16:44 UTC, Asad-noor commented on migrations/0001_add_tables.up.sql
> +          ON DELETE CASCADE
Why would we delete from category table? And if you delete then how would you manage the field category_id on user table with corresponding category id? As we discussed, we have to insert into category table first, then we will insert into user table with that id, so it should work for deletion like that! If it is not right, then I do not know about cascading, please let me know how it should be.

2021-07-02 16:53 UTC, shuza commented on migrations/0001_add_tables.up.sql
> +          ON DELETE CASCADE
you can delete category_id if its not used in user table. if you try to delete category_id which has reference in user table  then it will through db excaption

2021-07-10 17:20 UTC, rdhawladar approved these changes

2021-07-11 06:56 UTC, shuza approved these changes
lgtm

2021-07-12 04:35 UTC, merged