Feature/ap 4
teachmind/Auth-service pull request #9
Opened 2021-07-03 05:48 UTC by rdhawladar

User login

2021-07-03 09:22 UTC, shuza commented on internal/app/model/entities.go
> +func PhoneValidation(phoneNumber string) bool {
bind this method with user struct and do all validation in one method

2021-07-03 09:24 UTC, shuza commented on internal/app/server/handler.go
> +	SuccessResponse(w, http.StatusOK, token)
return all user data with token

2021-07-03 09:25 UTC, shuza commented on internal/app/server/halder_test.go
> +		expStatusCode int
also need to check response data

2021-07-03 09:26 UTC, shuza requested changes
* need to check response data
* need to return user data with token
* do all login validation in one method

2021-07-03 16:11 UTC, rdhawladar commented on internal/app/server/handler.go
> +	SuccessResponse(w, http.StatusOK, token)
Returned all user data.

2021-07-03 16:11 UTC, rdhawladar commented on internal/app/model/entities.go
> +func PhoneValidation(phoneNumber string) bool {
Added single validation method for login.

2021-07-08 17:38 UTC, shuza approved these changes
lgtm

2021-07-08 17:39 UTC, merged